import "~/styles/globals.css";
import Providers from "~/components/Provider";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import TanstackProvider from "~/components/TanstackProvider";
import { ThemeProvider } from "~/components/theme-provider";
import { AppSidebar, AppSidebarSkeleton } from "~/components/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "~/components/ui/sidebar";
import { ModeToggle } from "~/components/add-toggle";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <Providers>
        <body>
          <TanstackProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SidebarProvider>
                <Suspense fallback={<AppSidebarSkeleton />}>
                  <AppSidebar />
                </Suspense>
                <SidebarInset>
                  <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
                    <div className="flex items-center gap-2 px-4">
                      <SidebarTrigger className="-ml-1" />
                    </div>
                    <div className="mr-4 ml-auto">
                      <ModeToggle />
                    </div>
                  </header>
                  <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                    {children}
                  </div>
                </SidebarInset>
              </SidebarProvider>
            </ThemeProvider>
          </TanstackProvider>
        </body>
      </Providers>
    </html>
  );
}
